// Code generated by lister-gen. DO NOT EDIT.

// This file was automatically generated by lister-gen

package internalversion

// AWSMachineClassListerExpansion allows custom methods to be added to
// AWSMachineClassLister.
type AWSMachineClassListerExpansion interface{}

// AWSMachineClassNamespaceListerExpansion allows custom methods to be added to
// AWSMachineClassNamespaceLister.
type AWSMachineClassNamespaceListerExpansion interface{}
