# The set of CRDs used by machine-controller-manager

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsmachineclasses.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: AWSMachineClass
    plural: awsmachineclasses
    singular: awsmachineclass
    shortNames:
    - awscls
